apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:rVxlGR1kuvVVl2s6+FycwgViex9bpmsJefkCNqEvqGUlWp8uI2mV8Q==,iv:4eSwfdOzC1J7mZ4oM32sR7AQ5YVW/JmHEMSOq1vc9VY=,tag:+NUFRvHvTCjG50gCGR3Ptg==,type:str]
sops:
  age:
    - recipient: age1cjkplkjxer6ycgqujzxy7ekn7y6k89482jgy9l7cayxncsfnhpnqea8e4a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNEMyTmlCMlVteTArYndG
        dVZwNDZ1eFdjUmMyZ2Q4TGdNaHRwODZ0MkVZCkp3S1Q1L1RHeXlGQU81VDVhSDU3
        UXgvS00yeEZ3QWVYcEdkSzBQdHB0T0EKLS0tIGVhWkh6THloMzJsQkkwYjRtNmM0
        eDRuQjRLMnFGOVRnZGxJVk9JcEg2QWMK5eHWhRu96NmDMwMV9pZ/9J0uxyEJNzjk
        iY3A0DMFIrGtiiVAp8UmeAEjoQdqYyBS95DeYVfIXfkRYa9ePVCLVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T06:08:33Z"
  mac: ENC[AES256_GCM,data:PKD9+KYljsUmXh0Kbd1/VcTruaWzUElwOWuUWnAbLIuayNBauKb03x+kSU1qW9XkILLcI+Go2AiadLDOAgcVwsGmTfVcO7zlu2FmeDCX09+1wtROFh81Dt65YeYWW7tiKzoKc05SQcrdSGln6KR2nt9ifwwrdHiM3tremGk7GZg=,iv:rZwyveWedairLKLF/pEXhtmQNRp310oAf14QJJkq6RY=,tag:GcvmuB8XAuV9OxmOqrWZAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
