apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:cQtARHIMHVlhj/nUi5ut0r82vfcbveemDHn3J8myWFR3n19UsA45yA==,iv:lvWHdXMuxhSEuu3gdmvi4UFP4IrTPdxcImSUVtWLWhA=,tag:PmkRveFp3VjdD4+Kpw0dvA==,type:str]
sops:
  age:
    - recipient: age1cjkplkjxer6ycgqujzxy7ekn7y6k89482jgy9l7cayxncsfnhpnqea8e4a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUUJ4UW9uYVFNNURWcGFG
        L1VocWJZdmRkZGlTUmdnMzBteHJjQUZGbVZVCjl5TUtlL1FoRUo3RU4ya1hUYm1o
        eGt4UVFvSjBTMGZNQXZwdWtHZCszQVEKLS0tIEdqNmVyUEJRbVFKaWQvYUpXS1Ja
        ejJidHM3bXhncng5cFFkZzhPbXpTUW8Kb5WzkSiOMxCwLO5jE325n4rkAH/KhBN1
        +kfAhyRuHS7gizVgFJ46iP+E+sD0Iy1i6oxdhS0m2G0P37xYTRr1mw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T11:13:22Z"
  mac: ENC[AES256_GCM,data:eZX6t/PTrA9rEfDJz2tkgTcggpCaNATW8YKSMHhOQRWP7KmZkaSegSSTQw+ta4wnTsfrY7ZHyzY/FJJqLrShVNlrPuW2ibfPxWrkUNbBHdTLTAtWt9mOR1ahmYTiZ3uOAAeXa1MtyWPXMdmjStLjVIBllRu/e3BXqjxjBV3tipg=,iv:CWrhijvoFSokM7tP5/YcGU9us0ttJP1sqmFX1oJhI/Q=,tag:NOeGynDFj+FxVT95f1ZuNQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
