apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:TvsZvmQZwyMyJoCLouVRhOM7GjSdE2te3GIxExRVOpvvndCrrs626A==,iv:es4Bv11uiIUy9w/oge8Mg2IalylomrS81eBhwy8ujr4=,tag:awDXxQfSpNhLqCAspLEYmA==,type:str]
sops:
  age:
    - recipient: age1cjkplkjxer6ycgqujzxy7ekn7y6k89482jgy9l7cayxncsfnhpnqea8e4a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMUZTUWZsdHhiWTk0Y1Zl
        K2NjSi9pR3dEMm43MFBNNzNtTkRSS1Z1b0ZzCmhEWndydUdzMHF1YXAxSzhicGJ2
        K0ozcXJrT1hwMHJYNVF6K2hjc0tHVncKLS0tIFMvNEFMQVBqQzgrbUo3Q0dNSTBL
        dnMyRDVQSkRscit4Yy9PdG83OEVzNU0KljJpNW66M5ITpP0pmhMe5u6Zd/Gf9vQy
        DYfy9SSGyG6bvaPB12TtbiNiC0YpSJI8k1odgIjKaKer+vd9SzbkZg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T11:18:47Z"
  mac: ENC[AES256_GCM,data:W6JW95nhLuXSV0X9XeKEQT+UFPjziOpitg49K6UKcDrzZYkUXg3g7KGGBC3zNvwH+NzUCjmbxRPYLeJGaj3/+h5xaHvKA+m09flaZCxWnbO4aT4kGRlEIlrwlx0EcJMoSDmFLD88TSkOJtC9YRON/68tNQD1C4bxgc5OHt/4FuU=,iv:wn/3Idct/S2flsB31gtENgBZb489ICS6oOwJwSx4jHM=,tag:STETkGKwEAPncB+8iPJCrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
