apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:n9C1BB/pRga0C/IL8Dx2,iv:R759+31UsU1gY6uj5iRWNfmmtWTeV9psBCwl+8hC9Tw=,tag:QQsEME9mEQwtLqgQIHE+Ag==,type:str]
sops:
  age:
    - recipient: age1cjkplkjxer6ycgqujzxy7ekn7y6k89482jgy9l7cayxncsfnhpnqea8e4a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTU9GdXZKZDVvV2dqMzJX
        a1ZnQ054VlVEcEZESzF6d0RxQW1LRlRNL25zCktOZjBPOHg0THVRcUN4ZDdTallF
        K1JnSks1eW1FeEgzR2dKNDBzcXB2RW8KLS0tIHBCQ1BqUlJIZStMdEJ5UVJBcUdC
        SkhLS0NwZjlXakIzSnVNOXdJVkp4SEEK5HMURiTakvlFw6Yjwq6m/FKjJ3HL+87t
        6L4dqdRoczk2sOcCNM28QYbYzACyzmDolxi8FdjBSpOAflhmsOmzqA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T11:13:22Z"
  mac: ENC[AES256_GCM,data:aZjRknhMYlHMYUfJOLYz3ZEzJAFdrANX44/UmaYWpEC57U7I/3/GG39G5PEE3MhyjYHMIJ3Fh/m9g3GJJ3C+35fANLqCRfSB5bWTrdQJFVL8DxyOk0bIXf59RumQCPByTda/5aH5kiPAy6mbVeQHOQ4AA8pREwAF/1rIdpYHCog=,iv:gDwltAVja4y16eI6cLQbjSWhDWX6qQE2s8PUtkPzR9o=,tag:ddVqwzEIIKOSeHYl+hxKCw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
