apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:3MxHJrRXdg2KjijmiVOw,iv:ZgplZYNgdu8MvLFiCwA4TEPcdESIlxyvy+yVLazGQZ4=,tag:HcfqK8tl5j+8Q5lXgZHm3g==,type:str]
sops:
  age:
    - recipient: age1cjkplkjxer6ycgqujzxy7ekn7y6k89482jgy9l7cayxncsfnhpnqea8e4a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTK3MrNWNZQWFUWGNJWk12
        Q2hnRi9lUC90RWZMSzlEbm5wZDdxUE5KRXdFCldCQVRZOUFHZnJJMUc0cWNUTnpv
        aGtleis2dXdqMlZHQStlTU5uZ0l2cTgKLS0tIFMvUVZJa0N5LzMvNVdVZDZXc1pm
        TTJzLzFjN3BsM1VGWUcvcjNtTHNuQ2cKUJyYbjhU/ZJoMbjdAdqSS9YF09Iiv2M/
        RUn3c9MIVp9gHspI46H6s6UVoQcC5UQDsCD1VMcjtldmLDlGDDAllw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T06:08:33Z"
  mac: ENC[AES256_GCM,data:t9WPXKoXx9KWCrxEEyXHKvW+FNwO0QU4mhY2i/PrNBHn7BedCq8Ry74udySykA1uB2INnWOnPybXGpo5+kIShZ2ABTVNf8IyR83rwfWmXI/qOLrAxuUMpVZMR7OaSQjw3RFGhXsq7hn/0EwMWoBcVWP4AMMe/OONmpIBL7f36dc=,iv:wLqeKSARx86qV7N5v2TK3HMjNxkgBC6CRdwI6Btfq3Y=,tag:yYlykKgtofObhkM/9+S8jQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
