apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:c9Aq8EC3D2wmpaarLs+0,iv:m/ENTqZUPydCeYDDalTcN19hlWoDv3gfdPGQyTKUYZk=,tag:bJ8JVIvQW+Zf5mA6neAR7g==,type:str]
sops:
  age:
    - recipient: age1cjkplkjxer6ycgqujzxy7ekn7y6k89482jgy9l7cayxncsfnhpnqea8e4a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqamcrSTUvNnI1SVFBNng3
        dU1CQzhPKzBIek5xbUdQS1hhZkp2Y05Dend3CnQrWCtBdXY1WEdHMDNpdFFJOFhU
        Wm9mdjV6WXQ4L3dieG1mZG1JaGFuZVEKLS0tIG5VNGg4UG1ZdWlQdUQwV1I5NEs1
        ZDZRdGh2eUE1b0ZNS3VHMzNMcmRpSWsK5F789NxkeIBMMwmkzqv38Ddx2ZqU0Oyv
        lpmpXWAfMIrC554osWy3BggnFXHmdo9RdCTsF6W8jvZ0zeU92XHw/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T11:18:47Z"
  mac: ENC[AES256_GCM,data:kvyjumpcPlegVDviYY0yPShzNSGTag27CARLrXvGSMMXwBntVrpyimPTOCBySS7vbXN/kDHPgzMi5ZZVyqrF03ZNE/VWx5VlnPy6759vKDtslMbNnpST0aIk4vqdWJi50mf03B2zhvf5qaeftC/n/7HIsz6lC+DjRDqZdqqfCag=,iv:xNePDbRgDAHFnHSC0CdzBsiWG5FcjJAMFFRRCVr8c6U=,tag:S5Ga/OMay0LWiubPCvXORw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
