apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Hi2VHCZznTdCfAnG2K+wwwvkiUIytmBHwHiBe6wO8So=,iv:WA0P3ENdFGPTZAeYJxA0Ja1xnH0Ju76+EVFNVaH/ii0=,tag:anhHaIXczk/yhfIlwHKuCQ==,type:str]
sops:
  age:
    - recipient: age1cjkplkjxer6ycgqujzxy7ekn7y6k89482jgy9l7cayxncsfnhpnqea8e4a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUckhsc051anF0K1VYWWFq
        eGFTK2xHQVpRY3JYelJVU2xCeGVOZHU3S0hRCmFENlhMSElkYTJkTWJHUzlsUDlH
        TzFYczV6RzQzUzg4ZWVCVWJTZURveHcKLS0tIGJPVlRuOGZOOTBSMWQ0SzBIWVJH
        bmZVQ25jdFMrbjZoK3c2d0lMV2xSb1EKbiGNgSb6ElSDecRqLoAsjCOEHwPmVPdD
        2EgDNyAwnp7pYIym/aNk4+WV0iMalwyaOd+7NkPnv7uWKwScpnXO0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T11:13:22Z"
  mac: ENC[AES256_GCM,data:4XtDyEP7ZwGGmcNk1Z0Fi6sZH7yyEns8ZOGlpDAYmIWPqKfpLn21JmrvOqS1vIWy2dDlBHEiYdgliX75NLl/FLwG9XvhaWW1BVltvCGCkzcUYZlIBIva+2JCDXJDdyrvZkoeRyyQsGoFpz5kDTAxOZpQYZv/UY517m4tdvJWRVU=,iv:Ju1UIzDYTAB/pyo4lcbnHqPdUN91dXh3ozUnNQJssfk=,tag:NktDUOcxajKqRs2m8iML1Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
