apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:pGgnxcZSDPBAy+aNZJxEYThjZLYy0df1zDJ2jmXEdUg=,iv:mMf3avkLiXfByCRSFK5GPjRtHdvqMKtOKUI3MNCtjkk=,tag:RRBrN48GjRTmMH7ZNc3WdA==,type:str]
sops:
  age:
    - recipient: age1cjkplkjxer6ycgqujzxy7ekn7y6k89482jgy9l7cayxncsfnhpnqea8e4a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMSt6ckZGSnpIZHJRZjlC
        UlVTd2hCQTQ4ZjQ5Q0xBckYzSVNOQUNQUkRRClBSa2RoMFppNkNOSmhTbzliSVNw
        djcvWWhsOE1SYlE1eDl6VUV5b3RUb1EKLS0tIE5tSnZsSlBVMVZHQW1HWUVJWUVC
        Y3NUYWNvMmJCZWtiR083YlIwY3cxYXMKodHvZWE653a+ad23sHNVlmWkvxVFlfiW
        W3SoiRxRwmmtf0gDI0BRddTh84C7cYtQbXmnIrp3nww0N+5mmWscmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T11:18:47Z"
  mac: ENC[AES256_GCM,data:0yzLTrj4mNQ25+Pttgf7v01Q2IC/EsyAFN7yL111YMwUxZdz5E1mMg0anGlehrICjhxoKlJQu9a1jr8qhPJ/L6Z1O27S5h6ec26Fg8CgU7ON4LS4AVLxxXJ0jNrFMKK4qDHEskg454Me6wPcq+E7M51DZmtYGczs7szw6mehhok=,iv:EBK9pd5D+EJhwdjvbdnUmqPT3fsglybLbvnQYafblXo=,tag:1QEiXRHrq1oZo/Wq04z7pQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
