apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:UGpaJ5kejPpMURYoLkvHSU5i0pMICdKdV9wRCJgWgZ6uumYf9q89J41jxJjnR4SLHh82k+EqbpyaQzEss5P4skv9U+sOJnslrtUAb4v5Z7fWgSPmE6diYnkpNGp1PLua4XFvqOwg4RIzuKz08n0zlAWfdSi3mHC4z7YDe0ftGxwFElJY0A2LqBRP/yyvZCm0NB/8kaCPVQ0A826yxUTFn5pnxB7bjWaUagHZ/6taB0IxdXQE,iv:WvGLPsfA5Y+jgUU+tbch82kRiOhU+RQjUxByUEPvb+Q=,tag:mI5eByU9Xp1WODDnNk0XtA==,type:str]
sops:
  age:
    - recipient: age1cjkplkjxer6ycgqujzxy7ekn7y6k89482jgy9l7cayxncsfnhpnqea8e4a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVkMyZC9VSklQdWUrSjJE
        VFJVTTRFWFZkdVpQM1E4RnVmUDBhYkFiU2hjCmJVMXBoMHN6ZHpxanoraXFQZWM2
        WmJMTHFmRlM5UHFNOWVkanZ2Vlc2QzgKLS0tIGdNTUxBVlp2WUFEMHZZL3A1N0Jt
        dmRoSTFYSW1jTFg4STN0WlBncWk2NzQKj+H0JNR8R/Vgs4YTKxX3xXake8CKudPN
        tKErpb9bdJXudwRTKvD/k/a2Bfj5k09JRyGJRsiBHDx/TOFwgRhllw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T11:13:22Z"
  mac: ENC[AES256_GCM,data:5zTRv0P6Fq4q8lYk0jWnY+VVP9YSKfMo4WvFJH/dbdA0oZ1/lpAfrTIm2SkHAZpQRwtPNao1AG8cJYOgmNJIVEo8Xheht3deLYPOAExBB6qM3rsJC2xH7CVYJmDsRd7y2gLX//kEvEeUWfmtQNHTu43n0YVqc96KrxPp182fOeU=,iv:g/tdaNcTAswB1Cq2BGqvxgPlY0AZeUnY/AqUF8RGegc=,tag:r0yRXwK82EBauEJu3CA2kg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
