apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:QbsC980aMqrg0ocNJniZ9WLxhUwzQ1hIcPim03ElfCwioBH9Mv0TIEKBU1Tyv1TgAx6ZbB2HAyqA5oV573Ks/Ehjald/J5kOGIRA8sJ8Cjuw7weWb/4FrC6wFjHMvismbnrhx1SmRU4TF3SMAm9zXyp/xEVLdaNPC39ifC5Xwi/uEesGetfTQzXNlAt/lg6FZeU2gfjnHOcmBLykvpVwvmhAknQ9b0eTweRfNddAXjzVv989,iv:Vwb6pIUfJ5jGuiN/q3pVFTzolRUNIrZl+Np2lDzOdq8=,tag:G4ifQcJw+NRpcXEZXjalyA==,type:str]
sops:
  age:
    - recipient: age1cjkplkjxer6ycgqujzxy7ekn7y6k89482jgy9l7cayxncsfnhpnqea8e4a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXakJHdWg5UHBCVzROVHRx
        czBPQkp4TVhXUWtUeFhuZkVYbS9KWFZ1SWlFCkEwQmpDYW9seXplbGdMUVRjc1JG
        dEdpZ1MwMmRUTG5oOU03ejM3OVA2L2sKLS0tIHN4ZVdSYkNwWmJNY1ZqalVLY0Rx
        ZlVvbnhVTVlqNWJLTisvZ1pTbVlzYUEKwScmfnWJuYsUnFoEPe6EV+A7AZ26ypWq
        S5ubekQtVdnlQZpk9Ss3FhCgIF4KKqMpsmSn91PL/qrXfbJDBQDRtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T11:18:47Z"
  mac: ENC[AES256_GCM,data:lQq5Ch/NDONyEhPrGBWnf+syVhx0C5WprRxWwl5Eh4xLTArLqfTmzKy9arMofCTJn43tOFS7/Xf9y+Ze0drT8qE3l6LG9nxd9heffl6uwEa4Pe34yhulxGqbZSA8LBgLYrjfACNIavJfD1I44kMWoqWq4/7d2Tt6H/qi7XPeF5o=,iv:3XD28dEIGDfvYsjnBtcRHcrpYqNzFvxnVdxfgG+yqng=,tag:fbfx4C4dwf+dPzpWQ6rXdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
