apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Qk4OvMJ3FMsGX6CqHxOQHZbmKV1CDAAqgiiNltOd/xQkZw4K59ioyTKIXg+HgYYCh0u0ycVKq0v/vF3g9kkWvamtVeTa4ktq1FYuqNPsZpHcvN4I4n3OZYD+AsrcLQxJg4VxQN08n2EurXMEhA88ObxhJIciCV8GXpKKBU2lv1Jy0iDij7nNZKDxqJgqayNaMUt9utzK5yR+9U+66B/IlJMyIMBB3pQPOfm6yqaZLYZsI8+Y,iv:S2SRuzOLqUMpR/p9EpMIKUGOJ4abayC6wo5AvfnqB/o=,tag:qaQaZKGwxdkRa3HVTKkSZA==,type:str]
sops:
  age:
    - recipient: age1cjkplkjxer6ycgqujzxy7ekn7y6k89482jgy9l7cayxncsfnhpnqea8e4a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdmNqaE1mcXdqbTBJdDhk
        cU90TlN5Q3BWQ0YxNXRBNVhHOGl1Q1pEekZ3CjJjSEJmUFVIUW9nckpWOTUyNDRO
        c3hYV0l0aFplWFVwU00zQUFDM2NDNjQKLS0tIE1oWEZZYWlocWE5UXFoWEpMakJB
        UXRmeXZkUWMxZ210Qlh3dkZQMENZencK69+W+9urBpQSBRFp/fa1+wVb8U94ImjF
        MumoQDr5FZlJv7nKbKyTN5LIruUcxtIq7XWaIUv1T0nDcjTySvtu+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T06:08:33Z"
  mac: ENC[AES256_GCM,data:VcE+au0QFgFFomMICmfjJZgg2J+8aAMHLJN0YqfsknogeOUl2uThBLN3sd+jecSD52w6CahbZ/5ojfdDOQsnx0JG+v8it9axeV8ch4W+3UMMu72KpP7t0YWniXqPhMwvT1D87meSYW3vXHUBcDzKYReB646E44aDjyg+U2jwiT0=,iv:IgOTj/dL4YMJocvBQiyVjthTSABmatCmq46G9Wzq1SM=,tag:+lw3ZXFdFLW/rSsWi13ZKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
