---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: meshcentral
  namespace: network
spec:
#  dependsOn:
#    - name: external-secrets-stores
#      namespace: external-secrets
  path: ./kubernetes/apps/network/meshcentral/app
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app meshcentral
#  components:
#    - ../../../../components/volsync
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  postBuild:
    substitute:
      APP: *app
      APP_UID: "568"
      APP_GID: "568"
#      VOLSYNC_CLAIM: meshcentral
#      VOLSYNC_CAPACITY: 5Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
