apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:77MTj4lasAGzVmwC1i3y/HFBQOr5J8nuOOd512zwQeoqwbh+GnxmWg==,iv:s5kXOcole9ggnZG6++JmITNew6CiaXegX6zRXcc6iRU=,tag:h28n3dsMQ78hQDDt2KhbaQ==,type:str]
sops:
  age:
    - recipient: age1cjkplkjxer6ycgqujzxy7ekn7y6k89482jgy9l7cayxncsfnhpnqea8e4a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpa1Yvek9DUy9xd2FkdmRY
        V0xFUnlrcm1yUEIxeFhJZnpOYlZTc0JSL2lVCkMrWW1HUjl6S2g3Sm52YWRLemZC
        YTN4UTFLYlhMOWVka2tkMnJQK1lad0kKLS0tIHpML3BsWktyRVF0TGhKV2I2Wmln
        bnhxbVA5cm5na25VV1YzVmNWRFNsTmMKgeWpvp1ftPSW833VQ4CVCiYUiidODd4c
        TvKS2oEHt3YiIJ3Nwx0+tu7NIrbckddIWzVT5Owz68sYGGKtA/ebmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-17T06:08:33Z"
  mac: ENC[AES256_GCM,data:v/I0uRorTFCU7era7PWWgoHg6oHeTOc2rMV/0Pyw0UqkJOmCxy96jLcw2tVjsYKw6oZj+S2ZviMEYOXKVAjVh4F/UeU3bxrWjg2r3OS2sIjJAov1XGixz48UvhpiLo+c9N2fMx5YrfGwd3blmTLRQdkMZzMA5qr10RT31Df1Y4k=,iv:24r/L0m3wgE0Q/zsZmxFb9oIp4WrCj8uI6/RYpuId0A=,tag:2QpdKYtCVJZjvHdkpZJa7A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
