apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:YHVkdnNFDsx6h2yAzXIl20+jejRUtxKkDMC56miQzGwSwHxWAy7kfg==,iv:wLrWF5mspggG/143lyjOHDRo+23U2/a2ZUo8j6DqBTI=,tag:Md9ZzFEdVaj8iSyE353kbA==,type:str]
sops:
  age:
    - recipient: age1cjkplkjxer6ycgqujzxy7ekn7y6k89482jgy9l7cayxncsfnhpnqea8e4a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVkExZUJ6WmRzSHQyeWVF
        cE93aktKUG81RFpLTGppM2RZQ2x3NEtHbzNnCmFHTWt2c2pRQ2p6YmdKdnNvWFgz
        T0JPTlpBR2xWaGkyVXQ1M3l1SHI3RUUKLS0tIHVaeHNHOFR6NDBvczhXMTVLWGpl
        d3kwZXl6S3ZkSWJ1c3RQcWhxWVdqa0EKXOX6XgLV50XpSZlP5xQFn8sOYEODt67x
        7ruqDVKwTVvhxKMl30rg/ekdpZctnoq72X5AU2ZH0ccjNAc+BtgKmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T11:18:47Z"
  mac: ENC[AES256_GCM,data:YA3dokTj392WjsXyrxoU83l7rMbLQycN5LpbIvCe1jC11QEQSxoOLDdf0SPdFEw/JZSuDwa/JE/kS+0I4dlab9q+vqAvZAaaKL7gE434cSE6loIwwV5NjreMESPQRm0wC1iejn/Y+F2TXJ06BO6ita+kZWXeCcejl+gAIW3EVgI=,iv:7wsiOL/RRoL5OfewXG7OtmvfA9AgUkFmOJGRmoPTZ2w=,tag:4FTtfmsEIJ3dOLDnRmPQ/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
