apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ppAqIa5c1qXy5GeSyJKIUo1hHRFFJbybrBfcetsaU/nXz03sy/xMKw==,iv:MxxrVss6OJrjgdaNAA7ho2Gh2TSVi7IZ9cQr6Ests7Y=,tag:XRV3u5VFswkuf+1RaUx8mQ==,type:str]
sops:
  age:
    - recipient: age1cjkplkjxer6ycgqujzxy7ekn7y6k89482jgy9l7cayxncsfnhpnqea8e4a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dGNHRGpMbFBUUkVFUC9C
        dmt6M05OY3dvNUFaR21OaTlhM1FqdFpMWHhZCnZuRjlDQXlaUnRTU05JK3JaaE1u
        K0tFdHphRnoxa1QxQTdiWW1zaklDa0kKLS0tIGFneTRaYjAvbUhUSHlNcjBMdGhN
        QXpINFQ2YlhOUFM4WjBUektXUVhxQUUKvQ8txzxtcKzFURhOquDIrnCYcP09pCKz
        Phhv+sYFA47X8XVah2aCtnHgWHPx+rbDMU24h9co+u85kGK7yxtEEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T11:13:22Z"
  mac: ENC[AES256_GCM,data:8o1rm0M1HonwWbgn5VQZrjDbiUpap86/Ul6m9mxtkGv+SRxfVnpwcnE6LuRgufC28UlBd3NDk/xbj1aFIsWmAbno5wno7mx42f5ANlYgVDMTfS8mOFo9WthFmOj5KZwMFuF/v7BZIy0o2mdW+h4AMHinPttu76hzAvXKDosDPIo=,iv:Wuz3ezCgGu8VlHeoc4nw7I6QT9bxHY6DcWYQAGbjZQw=,tag:80AdH6gNV86VUT8WudAe1g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
